[package]
name = "splitmailbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
maildir = "0.5"
chrono = "0.4"
log = "0.4"
simple_logger = "1.13"
